name: Update Submodules

on:
  push:
  pull_request:
  schedule:
    - cron: '0 22 * * *' # Every day at 22:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Update submodules
        uses: ./
        with:
          reviewer: itsapinhulk
