name: Verify

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  vendored-in-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify vendored script is in sync
        run: bash test/check-vendored-script
